### ISSUE TITLE
A way to sync notes across computers

### ISSUE THREAD

**Issue by ghassan0** [vixalien/sticky#101] opened 2023-11-07 06:28 UTC
It would be really nice to be able to easily sync notes across devices. I'm not asking for a built-in syncing mechanism as it would probably be out of the scope of this project. But I would like to be able to use something like Syncthing to sync the folders where the notes are stored. This would also allow for an easy way to backup my notes. 

Currently whenever a "foreign" note gets added to a computer while the Sticky Notes app is already open, it doesn't show up. And after I close the app, that note gets deleted.

**Comment by vixalien** [comment] 2023-11-10 10:45
Indeed. You need to move your notes while Sticky Notes is not open. I will be fixing this issue in v1

**Comment by TriVoxel** [comment] 2024-02-12 07:46
Actually, I am asking for a simple syncing mechanism. The benefit of Sticky notes is it makes it easy and pain-free to quickly jot down an idea without worrying about anything, however, I never realized that it would be so impractical once I was using it on multiple devices. Would honestly be amazing if there were a simple peer-to-peer syncing feature on the local network, perhaps with a basic username/passcode. Might sound complicated, this app would seriously benefit from easy syncing.

As an alternative, it would at least be nice to be able to share notes by exporting them (with all the formatting in-tact) via an export/import system!

**Comment by BeatLink** [comment] 2024-02-12 12:41
The fastest and easiest way to do this would be to sync it to a text file on the local device. That opens you up to not only several sync companions such as syncthing, dropbox, google drive, onedrive etc but also several note applications such as Simple Notes or Markor on android

**Comment by joaocandre** [comment] 2024-05-23 17:06
> The fastest and easiest way to do this would be to sync it to a text file on the local device. That opens you up to not only several sync companions such as syncthing, dropbox, google drive, onedrive etc but also several note applications such as Simple Notes or Markor on android

I'd also add WebDAV to that list.

I've also noticed that some of those Android apps are limited to active import/export operations instead of passively monitoring a directory on the device (Markor is one exception IIRC).

For simplicity, supporting Markdown (#89), with a custom directory holding individual markdown files for each note, that each user would synchronize as intended (it's quite straightforward to configure e.g. syncthing for that)  would be a reasonable first step towards that.

**Comment by vixalien** [comment] 2024-05-23 19:22
> For simplicity, supporting Markdown (#89), with a custom directory holding individual markdown files for each note, that each user would synchronize as intended (it's quite straightforward to configure e.g. syncthing for that) would be a reasonable first step towards that.

indeed, that's the plan.

**Comment by vixalien** [comment] 2024-06-01 22:53
I'm closing this to focus on #89 first, when notes are saving as markdown, we will discuss syncing later

**Closed by vixalien** 2024-06-01 22:53 UTC
