### ISSUE TITLE
Notes dont safe 

### ISSUE THREAD

**Issue by soentyp** [vixalien/sticky#76] opened 2023-06-15 15:12 UTC
After i create a new sticky note and close it again it is not saved and i don't see any option to save it either. 
I use the latest release Version 0.2.1

**Comment by vixalien** [comment] 2023-06-15 17:02
are you creating an empty note? empty notes do not get saved.

**Comment by soentyp** [comment] 2023-06-15 19:56
> are you creating an empty note? empty notes do not get saved.

Yeah I guess so, but I don't see any other option.

**Comment by forkentiney** [comment] 2023-06-16 04:40
I too am having this problem. I have installed the application, opened it, created a note, typed on it, closed it, and found that it did not save. In the main window where all the notes should appear, the note is listed as an "empty note" although it is clearly not empty. Is there something obvious I'm missing? Is there a way to save the notes I've written on? If this is obvious, could someone please direct me to some documentation where I can learn how to use the app properly? See attachment for a visual of this information. 
![image](https://github.com/vixalien/sticky/assets/136779764/824352e1-9dfb-478a-aba3-7d9fedfdcdc6)

**Comment by vixalien** [comment] 2023-06-16 15:54
you are not using the app incorrectly. there seems to be a bug

**Comment by vixalien** [comment] 2023-06-16 16:01
I can confirm the bug. working on it

**Closed** 2023-06-16 16:18 UTC
